camunda1:
  bpm:
    client:
      base-url: ${CAMUNDA_REST_URL} //https://camunda25.f4.htw-berlin.de/engine-rest
      worker-id: emotion-slack-worker
      lock-duration: 20000
      async-response-timeout: 10000
      basic-auth:
        username: ${CAMUNDA_USERNAME1}
        password: ${CAMUNDA_PASSWORD1}

slack:
  bot-token: ${SLACK_BOT_TOKEN}
  channel: ${SLACK_CHANNEL}

ors:
  key: ${ORS_KEY}

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks