camunda:
  bpm:
    client:
      base-url: ${CAMUNDA_REST_URL} //https://camunda25.f4.htw-berlin.de/engine-rest
      worker-id: emotion-standort-worker
      lock-duration: 20000
      async-response-timeout: 10000
      basic-auth:
        username: ${CAMUNDA_USERNAME} //"05"
        password: ${CAMUNDA_PASSWORD} //"HTWberlin1."

slack:
  bot-token: ${SLACK_BOT_TOKEN}
  channel: ${SLACK_CHANNEL}
